name: ink_page_indicator
description: Page indicators for Flutter including an implementation  of the InkPageIndicator.
version: 0.1.2
homepage: https://github.com/bnxm/ink_page_indicator

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: