name: ink_page_indicator
description: Page indicators for Flutter including an implemenation of the InkPageIndicator.
version: 0.1.1
homepage: https://github.com/BendixMa/ink_page_indicator
repository: https://github.com/BendixMa/ink_page_indicator

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: